CREATE TABLE _Instance_Weapon (
  Guid BLOB PRIMARY KEY ON CONFLICT REPLACE,
  _ID TEXT,
  _Level TEXT,
  _Layers TEXT,
  Transform BLOB,
  Id TEXT,
  Graphics TEXT,
  IsCharGraphics INTEGER,
  AnimSet TEXT,
  Physics TEXT,
  Name TEXT,
  LookAtText TEXT,
  EquipmentType TEXT,
  WeaponAnimGroup TEXT,
  AlternativeWeaponAnimGroup TEXT,
  TaAttr TEXT,
  SoundSet TEXT,
  WpW6 INTEGER,
  WpW6plus INTEGER,
  WpTPKK1 INTEGER,
  WpTPKK2 INTEGER,
  Gew INTEGER,
  WpLg INTEGER,
  WpBF INTEGER,
  WpINI INTEGER,
  Value INTEGER,
  WpATmod INTEGER,
  WpPAmod INTEGER,
  WpDK TEXT,
  WpATRange REAL,
  WpReload INTEGER,
  WpD1 INTEGER,
  WpTP1 INTEGER,
  WpTP2 INTEGER,
  WpTP3 INTEGER,
  WpTP4 INTEGER,
  WpTP5 INTEGER,
  QuestId TEXT,
  PickingRange REAL,
  WpAmmoCategory TEXT,
  WpAmmoGraphicsAttr TEXT,
  MaxStackCount INTEGER,
  StackCount INTEGER,
  ScriptPreset TEXT,
  ScriptOverride TEXT,
  LimitedScript TEXT,
  PermanentEffect TEXT,
  CanUse INTEGER,
  CanDestroy INTEGER,
  IconBrush TEXT,
  LookAtUnidentified TEXT,
  IdentificationTalent TEXT,
  InfoUnIdentified TEXT,
  InfoIdentified TEXT,
  IdentificationDifficulty INTEGER,
  IsIdentified INTEGER,
  IsMagical INTEGER,
  Robable INTEGER,
  PickingHeight REAL,
  UseAnim TEXT,
  Characteristica TEXT,
  SoundUI TEXT,
  StorageGUID BLOB,
  Lootable INTEGER,
  VelocityVector BLOB,
  PhysicCategory TEXT,
  StorageSlotId INTEGER,
  IsTradeItem INTEGER,
  InventoryType TEXT,
  IsEquiped INTEGER,
  EquipmentSlotId TEXT,
  SpellTargetOffset BLOB,
  LocalizeLookAtText INTEGER,
  IsSplitting INTEGER,
  InfiniteStack INTEGER,
  UseTalent TEXT,
  EntityDiscovered INTEGER
);

CREATE INDEX _Instance_Weapon_Id ON _Instance_Weapon ( Id );
CREATE INDEX _Instance_Weapon_Name ON _Instance_Weapon ( Name );
CREATE INDEX _Instance_Weapon_StorageGUID ON _Instance_Weapon ( StorageGUID );
CREATE INDEX _Instance_Weapon__Level ON _Instance_Weapon ( _Level );
