CREATE TABLE _Instance_Armor (
  Guid BLOB PRIMARY KEY ON CONFLICT REPLACE,
  _ID TEXT,
  _Level TEXT,
  _Layers TEXT,
  Transform BLOB,
  Id TEXT,
  Graphics TEXT,
  Physics TEXT,
  GfxSkin TEXT,
  Name TEXT,
  LookAtText TEXT,
  EquipmentType TEXT,
  RSKo INTEGER,
  RSBr INTEGER,
  RSRu INTEGER,
  RSBa INTEGER,
  RSLA INTEGER,
  RSRA INTEGER,
  RSLB INTEGER,
  RSRB INTEGER,
  ArMaterial TEXT,
  ArTyp TEXT,
  ArGes INTEGER,
  ArBE REAL,
  QuestId TEXT,
  Gew INTEGER,
  PickingRange REAL,
  Value INTEGER,
  ScriptPreset TEXT,
  ScriptOverride TEXT,
  LimitedScript TEXT,
  PermanentEffect TEXT,
  IconBrush TEXT,
  Arme INTEGER,
  Haende INTEGER,
  Torso INTEGER,
  Beine INTEGER,
  Fuesse INTEGER,
  Haare INTEGER,
  LookAtUnidentified TEXT,
  IdentificationTalent TEXT,
  InfoUnIdentified TEXT,
  InfoIdentified TEXT,
  IdentificationDifficulty INTEGER,
  IsIdentified INTEGER,
  Robable INTEGER,
  PickingHeight REAL,
  UseAnim TEXT,
  CanUse INTEGER,
  Race TEXT,
  Sex TEXT,
  StorageGUID BLOB,
  Lootable INTEGER,
  VelocityVector BLOB,
  PhysicCategory TEXT,
  StorageSlotId INTEGER,
  SoundUI TEXT,
  IsTradeItem INTEGER,
  InventoryType TEXT,
  IsEquiped INTEGER,
  EquipmentSlotId TEXT,
  LocalizeLookAtText INTEGER,
  IsMagical INTEGER,
  CanDestroy INTEGER,
  UseTalent TEXT,
  EntityDiscovered INTEGER
);

CREATE INDEX _Instance_Armor_Id ON _Instance_Armor ( Id );
CREATE INDEX _Instance_Armor_Name ON _Instance_Armor ( Name );
CREATE INDEX _Instance_Armor_StorageGUID ON _Instance_Armor ( StorageGUID );
CREATE INDEX _Instance_Armor__Level ON _Instance_Armor ( _Level );