CREATE TABLE _Instance_Item (
  Guid BLOB PRIMARY KEY ON CONFLICT REPLACE,
  _ID TEXT,
  _Level TEXT,
  _Layers TEXT,
  Transform BLOB,
  Id TEXT,
  Graphics TEXT,
  Placeholder TEXT,
  Physics TEXT,
  Name TEXT,
  LookAtText TEXT,
  QuestId TEXT,
  Value INTEGER,
  Gew INTEGER,
  PickingRange REAL,
  ScriptPreset TEXT,
  ScriptOverride TEXT,
  LimitedScript TEXT,
  CanUse INTEGER,
  TaBonus INTEGER,
  UseTalent TEXT,
  CanDestroy INTEGER,
  IconBrush TEXT,
  MaxStackCount INTEGER,
  StackCount INTEGER,
  LookAtUnidentified TEXT,
  IdentificationTalent TEXT,
  InfoUnIdentified TEXT,
  InfoIdentified TEXT,
  IdentificationDifficulty INTEGER,
  IsMagical INTEGER,
  IsIdentified INTEGER,
  Robable INTEGER,
  PickingHeight REAL,
  UseAnim TEXT,
  TrapId TEXT,
  StorageGUID BLOB,
  Lootable INTEGER,
  VelocityVector BLOB,
  PhysicCategory TEXT,
  StorageSlotId INTEGER,
  SoundUI TEXT,
  IsTradeItem INTEGER,
  LocalizeLookAtText INTEGER,
  IsSplitting INTEGER,
  InfiniteStack INTEGER,
  SpellTargetOffset BLOB,
  EntityDiscovered INTEGER
);
CREATE INDEX _Instance_Item_Id ON _Instance_Item ( Id );
CREATE INDEX _Instance_Item_Name ON _Instance_Item ( Name );
CREATE INDEX _Instance_Item_StorageGUID ON _Instance_Item ( StorageGUID );
CREATE INDEX _Instance_Item__Level ON _Instance_Item ( _Level );
