CREATE TABLE _Instance_Shield (
  Guid BLOB PRIMARY KEY ON CONFLICT REPLACE,
  _ID TEXT,
  _Level TEXT,
  _Layers TEXT,
  Transform BLOB,
  Id TEXT,
  Graphics TEXT,
  Physics TEXT,
  Name TEXT,
  LookAtText TEXT,
  EquipmentType TEXT,
  Gew INTEGER,
  WpINI INTEGER,
  Value INTEGER,
  WpATmod INTEGER,
  WpPAmod INTEGER,
  QuestId TEXT,
  PickingRange REAL,
  WpAmmoCategory TEXT,
  MaxStackCount INTEGER,
  StackCount INTEGER,
  ScriptPreset TEXT,
  ScriptOverride TEXT,
  LimitedScript TEXT,
  PermanentEffect TEXT,
  CanUse INTEGER,
  CanDestroy INTEGER,
  IconBrush TEXT,
  LookAtUnidentified TEXT,
  IdentificationTalent TEXT,
  InfoUnIdentified TEXT,
  InfoIdentified TEXT,
  IdentificationDifficulty INTEGER,
  IsIdentified INTEGER,
  Lootable INTEGER,
  Robable INTEGER,
  PickingHeight REAL,
  UseAnim TEXT,
  SoundSet TEXT,
  ArMaterial TEXT,
  StorageGUID BLOB,
  VelocityVector BLOB,
  PhysicCategory TEXT,
  StorageSlotId INTEGER,
  SoundUI TEXT,
  IsTradeItem INTEGER,
  InventoryType TEXT,
  IsEquiped INTEGER,
  EquipmentSlotId TEXT,
  SpellTargetOffset BLOB,
  LocalizeLookAtText INTEGER,
  IsMagical INTEGER,
  IsSplitting INTEGER,
  InfiniteStack INTEGER,
  UseTalent TEXT,
  EntityDiscovered INTEGER
);
CREATE INDEX _Instance_Shield_Id ON _Instance_Shield ( Id );
CREATE INDEX _Instance_Shield_Name ON _Instance_Shield ( Name );
CREATE INDEX _Instance_Shield_StorageGUID ON _Instance_Shield ( StorageGUID );
CREATE INDEX _Instance_Shield__Level ON _Instance_Shield ( _Level );